services:
  web:
    build: .
    image: bwapp-php7:20240402
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - XDEBUG_MODE=debug
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./bWAPP:/var/www/html

  db:
    image: mariadb:10.6
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
      - MARIADB_ROOT_HOST=%
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
